services:
  server_dev:
    container_name: server
    user: 'root'
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend-network
    depends_on:
      - db
      - redis
  db:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    env_file: ./.env
    user: 'root'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
      - POSTGRESQL_REPLICATION_USE_PASSFILE=no
      - BITNAMI_DEBUG=true
      - PG_DATA_DIR=/bitnami/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/bitnami/postgresql/data
    networks:
      - backend-network
  redis:
    image: redis:7.4-rc2-alpine
    ports:
      - '9999:9999'
    networks:
      - backend-network

volumes:
  postgres_data:
    driver: local
    name: prolin

networks:
  backend-network:
    driver: bridge
